from typing import List, Dict
conflict_type:Dict[str,str] = {"alcohol": "addiction", "ayahuasca": "addiction",
                         "sedatives": "addiction", "tranquilizers": "addiction",
                         "hypnotics": "addiction",
                         "cocaine": "addiction", "dmt": "addiction",
                         "ghb": "addiction", "hallucinogens": "addiction",
                         "heroin": "addiction", "inhalants": "addiction",
                         "ketamine": "addiction",
                         "khat": "addiction", "kratom": "addiction",
                         "lsd": "addiction",
                         "marijuana": "addiction", "cannabis": "addiction",
                         "weed": "addiction",
                         "mdma": "addiction",
                         "ecstasy": "addiction", "molly": "addiction",
                         "mescaline": "addiction", "peyote": "addiction",
                         "methamphetamine": "addiction",
                         "dextromethorphan": "addiction", "dxm": "addiction",
                         "loperamide": "addiction",
                         "pseudoephedrine": "addiction",
                         "dimenhydrinate": "addiction", "pcp": "addiction",
                         "opioids": "addiction", "oxycontin": "addiction",
                         "hydrocodone": "addiction", "morphine": "addiction",
                         "methadone": "addiction", "xanax": "addiction",
                         "ambien": "addiction", "adderall": "addiction",
                         "codeine": "addiction", "vicodin": "addiction",
                         "dexedrine": "addiction", "ritalin": "addiction",
                         "concerta": "addiction",
                         "desoxyn": "addiction", "ephedrine": "addiction",
                         "psilocybin": "addiction",
                         "rohypnol": "addiction", "flunitrazepam": "addiction",
                         "salvia": "addiction",
                         "anadrol-50": "addiction", "oxandrin": "addiction",
                         "winstrol": "addiction", "anavar": "addiction",
                         "dianabol": "addiction", "equipoise": "addiction",
                         "aminoalkylindoles": "addiction",
                         "jwh-018": "addiction",
                         "synthetic cathinones": "addiction",
                         "bath salts": "addiction",
                         "tobacco": "addiction", "nicotine": "addiction",
                         "cigarette": "addiction", "cigar": "addiction",
                         "vape": "addiction", "vape pen": "addiction", }