suicide_words:Dict[str, str|dict] = {'bump': 'off', 'butcher': first_person_pronouns, 'cut': 'down',
                         'finish': 'living', 'ice': 'myself', 'knock': 'off',
                         'murder': 'myself', 'neutralize': 'myself',
                         'off': 'myself',
                         'waste': 'myself',
                         'whack': 'myself',
                         'claim': {'my': 'life'}, 'croak': 'myself',
                         'destroy': {'my': 'life'}, 'dispatch': 'myself',
                         'do': 'in', 'kill': 'myself', 'slay': 'myself',
                         'take': {'my': 'life'},
                         'annihilate': {'my': 'life'}, 'blot': 'out',
                         'decimate': {'my': 'life'},
                         'massacre': {'my': 'life'}, 'mow': {'myself': 'down'},
                         'slaughter': {'my': 'life'}, 'smite': {'my': 'life'},
                         'assassinate': {'my': 'life'},
                         'execute': {'my': 'life'}, 'martyr': 'myself',
                         'terminate': {'my': 'life'},
                         'euthanize': {'my': 'life'},'euthanatize': {'my': 'life'},
                         'put': 'down'}